### ISSUE TITLE
Pokecube / mc-1.12.2-pokemaster-4gb-r3 / balance issues

### ISSUE THREAD

**Issue by erlosdh** [P3rf3ctXZer0/MC-1.12.2-PokeMasterQuest-5GB#14]
I have id say 60+ pokecubes atm. Seems like the level difference does not matter when battling. I have watched my Level 30+ constantly lose to level 3 pokecubes.

**Comment by P3rf3ctXZer0** [comment]
by chance - would you be facing a mob with a purple flame?

**Comment by erlosdh** [comment]
Its not the mobs with flames
